= Quarkus - File Vault
:extension-status: preview

== Introduction

This project provides Quarkus [CredentialsProvider](https://quarkus.io/guides/credentials-provider) which extracts passwords and other sensitive data from Java `KeyStore`.

Java `KeyStore` is used as a file-based `Vault`. Sensitive data can be imported to and securely stored in this `Vault`as Java `SecretKey` values. 

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.file-vault:quarkus-file-vault` extension first.
In your `pom.xml` file, add:

[source,xml]
----
<groupId>io.quarkiverse.file-vault</groupId>
<artifactId>quarkus-file-vault</artifactId>
----

== Getting Started

First a Java Keystore has to be created and the data imported to it using a Java `keytool` and its `-importpass` option, for example:

[source,shell]
----
keytool -importpass -alias quarkus_test -keystore dbpasswords.p12 -storepass storepassword -storetype PKCS12
----

This command creates a keystore `dbpasswords.p12` with a secret key whose alias is `quarkus_test`.

== How to use the extension.

Once you have one or more keystore prepared you can use it with Quarkus extensions which integrate with `CredentialsProvider`.

For example, here is how you can configure it with `Agroal`:

[source,properties]
----
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
quarkus.datasource.credentials-provider=quarkus.file.vault.provider.db1

quarkus.file.vault.provider.db1.path=dbpasswords.p12
quarkus.file.vault.provider.db1.secret=storepassword
quarkus.file.vault.provider.db1.alias=quarkus_test

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql
----

In this example `quarkus.datasource.credentials-provider` refers to `FileVaultCredentialsProvider` as `quarkus.file.vault.provider.db1`.

The name format is `quarkus.file.vault.provider.<name>`, where `<name>` identifies a specific keystore configuration which in this case is:

[source,properties]
----
quarkus.file.vault.provider.db1.path=dbpasswords.p12
quarkus.file.vault.provider.db1.secret=storepassword
quarkus.file.vault.provider.db1.alias=quarkus_test
----

You can configure as many keystores as required.

Note setting a keystore alias (`quarkus.file.vault.provider.db1.alias=quarkus_test`) in the properties is optional. Instead you can pass it like this:

[source,properties]
----
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
quarkus.datasource.credentials-provider=quarkus.file.vault.provider.db1.quarkus_test

quarkus.file.vault.provider.db1.path=dbpasswords.p12
quarkus.file.vault.provider.db1.secret=storepassword
----

This is way you can refer to the same keystore but use a different alias each time.

`FileVaultCredentialsProvider` will return the extracted secret key as a `password` property. It will also use alias value to return a `user` property. The extensions such as `Agroal` will accept both properties. 

However, you can choose for only a `password` property be returned with `quarkus.file.vault.set-alias-as-user=false`. In this case you will need to configure a username with the extension specific property, for example, when working with `Agroal` you can use `quarkus.datasource.username`.

== Protecting the keystore passwords.

If you need to avoid setting a keystore password in `application.properties` then you can use a custom `ConfigSource`, for example:

[source,java]
----
package io.quarkiverse.filevault.it;

import java.util.Set;

import org.eclipse.microprofile.config.spi.ConfigSource;

public class KeyStoreConfigSource implements ConfigSource {

    @Override
    public Set<String> getPropertyNames() {
        return Set.of("db1.storepassword");
    }

    @Override
    public String getValue(String propertyName) {
        return "db1.storepassword".equals(propertyName) ? "storepassword" : null;
    }

    @Override
    public String getName() {
        return "file-vault-config-source";
    }

}
----

add `org.eclipse.microprofile.config.spi.ConfigSource` service provider entry listing `io.quarkiverse.filevault.it.KeyStoreConfigSource` to `META-INF/services` and then refer to the keystore password like this:

[source,properties]
----
quarkus.file.vault.provider.db1.path=dbpasswords.p12
quarkus.file.vault.provider.db1.secret=${db1.storepassword}
----

[[extension-configuration-reference]]
== Extension Configuration Reference

include::config.adoc[leveloffset=+1, opts=optional]
